services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: mi-api

    restart: always

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      - mariadb

    volumes:
      - ./uploads:/app/uploads

    networks:
      - app-network

  mariadb:
    image: mariadb:11

    container_name: mariadb-db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bossbudget

    ports:
      - "3307:3306"

    volumes:
      - mariadb-data:/var/lib/mysql

    networks:
      - app-network

volumes:
  mariadb-data:
    external: true

networks:
  app-network: